// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIJmrZdgF8xsohJ05cwxz8ppPlCTxEyfE',
    appId: '1:742518149784:web:2f1f08ce28a0990077b6ed',
    messagingSenderId: '742518149784',
    projectId: 'my-chat-ae5dd',
    authDomain: 'my-chat-ae5dd.firebaseapp.com',
    storageBucket: 'my-chat-ae5dd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwWeBCFowgOVf9t2iIh95X3rcPf6MGaQI',
    appId: '1:742518149784:android:c5569e49f66d291677b6ed',
    messagingSenderId: '742518149784',
    projectId: 'my-chat-ae5dd',
    storageBucket: 'my-chat-ae5dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArQTqB9PfDp0tDvSPxCkY2iWkRI8OfF5A',
    appId: '1:742518149784:ios:fde2cb3fca190abe77b6ed',
    messagingSenderId: '742518149784',
    projectId: 'my-chat-ae5dd',
    storageBucket: 'my-chat-ae5dd.appspot.com',
    iosBundleId: 'com.example.chatapp.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArQTqB9PfDp0tDvSPxCkY2iWkRI8OfF5A',
    appId: '1:742518149784:ios:64a271475fb3b65177b6ed',
    messagingSenderId: '742518149784',
    projectId: 'my-chat-ae5dd',
    storageBucket: 'my-chat-ae5dd.appspot.com',
    iosBundleId: 'com.example.chatapp.chatApp.RunnerTests',
  );
}
